// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RistoranteMVC.Persistence;

namespace RistoranteMVC.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RistoranteMVC.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("9bcd1113-6b23-4493-bc83-0c80a436430a"),
                            Name = "Pizzas"
                        },
                        new
                        {
                            CategoryId = new Guid("a4b49c2f-93b6-42c7-99c6-524638667afd"),
                            Name = "Pastas"
                        },
                        new
                        {
                            CategoryId = new Guid("c85f1ad9-cef4-4bab-94da-e4dfb466c158"),
                            Name = "Soups"
                        },
                        new
                        {
                            CategoryId = new Guid("10895537-2732-403b-87dc-047ec2535593"),
                            Name = "Desserts"
                        },
                        new
                        {
                            CategoryId = new Guid("d99c5243-4815-4722-9fe3-e27623b8232b"),
                            Name = "Drinks"
                        });
                });

            modelBuilder.Entity("RistoranteMVC.Domain.Entities.Dish", b =>
                {
                    b.Property<Guid>("DishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kcal")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Recommended")
                        .HasColumnType("bit");

                    b.HasKey("DishId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            DishId = new Guid("2589321d-a8bd-4b44-aaa9-7e7f7011c330"),
                            CategoryId = new Guid("9bcd1113-6b23-4493-bc83-0c80a436430a"),
                            Description = "Delicious classic from the pizza family",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 600,
                            Name = "Pizza margherita",
                            Price = 25.99m,
                            Recommended = true
                        },
                        new
                        {
                            DishId = new Guid("920c003c-15d9-4a64-87fa-f24fba522763"),
                            CategoryId = new Guid("9bcd1113-6b23-4493-bc83-0c80a436430a"),
                            Description = "The best for meetings with friends",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 750,
                            Name = "Pizza salami",
                            Price = 31.50m,
                            Recommended = false
                        },
                        new
                        {
                            DishId = new Guid("82d27ad9-138b-40b9-add2-54d4fbc5f815"),
                            CategoryId = new Guid("9bcd1113-6b23-4493-bc83-0c80a436430a"),
                            Description = "American pizza in the Italian version",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 800,
                            Name = "Pizza americana",
                            Price = 32.20m,
                            Recommended = false
                        },
                        new
                        {
                            DishId = new Guid("5174dcc0-0853-4500-8094-be9f8df8b5d2"),
                            CategoryId = new Guid("9bcd1113-6b23-4493-bc83-0c80a436430a"),
                            Description = "the best cheeses on your favorite pizza",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 900,
                            Name = "Four cheeses pizza",
                            Price = 33.90m,
                            Recommended = false
                        },
                        new
                        {
                            DishId = new Guid("fe07ee67-e796-4a87-bad8-e388677cdc5e"),
                            CategoryId = new Guid("a4b49c2f-93b6-42c7-99c6-524638667afd"),
                            Description = "The best pasta with classic bolognese sauce",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 450,
                            Name = "Spaghetti bolognese",
                            Price = 18.20m,
                            Recommended = false
                        },
                        new
                        {
                            DishId = new Guid("d68402ff-95f6-40a4-9fc9-1584f650678f"),
                            CategoryId = new Guid("a4b49c2f-93b6-42c7-99c6-524638667afd"),
                            Description = "Our kitchen's bestseller",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 550,
                            Name = "Spaghetti carbonara",
                            Price = 19.99m,
                            Recommended = true
                        },
                        new
                        {
                            DishId = new Guid("7d04d4d4-6d5a-4eeb-8732-18a12c3da0e0"),
                            CategoryId = new Guid("a4b49c2f-93b6-42c7-99c6-524638667afd"),
                            Description = "For more hunger",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 840,
                            Name = "Lasagne",
                            Price = 36.99m,
                            Recommended = false
                        },
                        new
                        {
                            DishId = new Guid("b971f859-5d2b-4a89-bd9c-0e314f77e325"),
                            CategoryId = new Guid("a4b49c2f-93b6-42c7-99c6-524638667afd"),
                            Description = "This taste will surprise you",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 410,
                            Name = "Tagliatelle with spinach",
                            Price = 19.99m,
                            Recommended = false
                        },
                        new
                        {
                            DishId = new Guid("7a5454a8-2716-4be6-946f-6784bec135e0"),
                            CategoryId = new Guid("c85f1ad9-cef4-4bab-94da-e4dfb466c158"),
                            Description = "Its taste comes from the best ingredients",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 180,
                            Name = "Creamy tomato soup",
                            Price = 12.99m,
                            Recommended = true
                        },
                        new
                        {
                            DishId = new Guid("907fd430-c17c-4226-b275-1182549acfda"),
                            CategoryId = new Guid("c85f1ad9-cef4-4bab-94da-e4dfb466c158"),
                            Description = "Our novelty",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 210,
                            Name = "Curry soup",
                            Price = 13.30m,
                            Recommended = false
                        },
                        new
                        {
                            DishId = new Guid("108320b7-6f59-4b64-bba1-67a4f60c00d5"),
                            CategoryId = new Guid("c85f1ad9-cef4-4bab-94da-e4dfb466c158"),
                            Description = "Tasty and nutritious",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 210,
                            Name = "Soup with meatballs",
                            Price = 15.95m,
                            Recommended = false
                        },
                        new
                        {
                            DishId = new Guid("b1f70ce6-d15e-4784-ab6f-675c643ae967"),
                            CategoryId = new Guid("c85f1ad9-cef4-4bab-94da-e4dfb466c158"),
                            Description = "Very aromatic dish that will delight everyone",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 210,
                            Name = "Mushroom soup",
                            Price = 14.49m,
                            Recommended = false
                        },
                        new
                        {
                            DishId = new Guid("dda205fc-cedd-4318-aab7-f397485ca5eb"),
                            CategoryId = new Guid("10895537-2732-403b-87dc-047ec2535593"),
                            Description = "The best dessert that will impress your other half",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 300,
                            Name = "Tiramisu",
                            Price = 10.50m,
                            Recommended = true
                        },
                        new
                        {
                            DishId = new Guid("9dd5b959-15ee-4a68-a04f-05ab599c2ca2"),
                            CategoryId = new Guid("10895537-2732-403b-87dc-047ec2535593"),
                            Description = "Melts in your mouth",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 290,
                            Name = "Panna Cotta",
                            Price = 10.40m,
                            Recommended = false
                        },
                        new
                        {
                            DishId = new Guid("57dbd2dc-9e46-4fdb-b783-140c464194c3"),
                            CategoryId = new Guid("10895537-2732-403b-87dc-047ec2535593"),
                            Description = "Sweet and cold what more could you want",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 260,
                            Name = "Ice-creams",
                            Price = 9.10m,
                            Recommended = false
                        },
                        new
                        {
                            DishId = new Guid("d363c5b1-5ca3-4b25-a91b-76dc8c63939c"),
                            CategoryId = new Guid("10895537-2732-403b-87dc-047ec2535593"),
                            Description = "It is worth a try",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 270,
                            Name = "Granita",
                            Price = 10.05m,
                            Recommended = false
                        },
                        new
                        {
                            DishId = new Guid("70481e18-636a-4324-8cf0-5f09ccfd42fa"),
                            CategoryId = new Guid("d99c5243-4815-4722-9fe3-e27623b8232b"),
                            Description = "Just good coffee",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 10,
                            Name = "Coffee",
                            Price = 12.99m,
                            Recommended = true
                        },
                        new
                        {
                            DishId = new Guid("77bec339-3c5e-417c-875c-2374d18b059d"),
                            CategoryId = new Guid("d99c5243-4815-4722-9fe3-e27623b8232b"),
                            Description = "Just good tea",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 10,
                            Name = "Tea",
                            Price = 12.99m,
                            Recommended = false
                        },
                        new
                        {
                            DishId = new Guid("6ab04d0e-e1ea-4633-9fa5-c6be43638979"),
                            CategoryId = new Guid("d99c5243-4815-4722-9fe3-e27623b8232b"),
                            Description = "Just water",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 10,
                            Name = "Water",
                            Price = 12.99m,
                            Recommended = false
                        },
                        new
                        {
                            DishId = new Guid("dd73a49b-efd4-4fa6-b2e8-21d3abef8831"),
                            CategoryId = new Guid("d99c5243-4815-4722-9fe3-e27623b8232b"),
                            Description = "Just Coca-Cola",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 110,
                            Name = "Coca-Cola",
                            Price = 12.99m,
                            Recommended = false
                        });
                });

            modelBuilder.Entity("RistoranteMVC.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = new Guid("99e4dc7c-6a01-4b86-8931-0c942699bb0f"),
                            Address = "Konopnicka 15",
                            BirthDate = new DateTime(2021, 11, 1, 22, 50, 32, 727, DateTimeKind.Local).AddTicks(3974),
                            City = "Cracov",
                            Email = "jan@mail.com",
                            FirstName = "Jan",
                            Gender = "Male",
                            HireDate = new DateTime(2021, 11, 1, 22, 50, 32, 730, DateTimeKind.Local).AddTicks(9622),
                            JobRole = "Cook",
                            LastName = "Fajny",
                            PhoneNumber = "111222333",
                            ZipCode = "32-200"
                        },
                        new
                        {
                            EmployeeId = new Guid("0b8758fb-c227-47c9-98a2-976d01732738"),
                            Address = "Rydla 59",
                            BirthDate = new DateTime(2021, 11, 1, 22, 50, 32, 731, DateTimeKind.Local).AddTicks(7662),
                            City = "Cracov",
                            Email = "ben@mail.com",
                            FirstName = "Ben",
                            Gender = "Male",
                            HireDate = new DateTime(2021, 11, 1, 22, 50, 32, 731, DateTimeKind.Local).AddTicks(7676),
                            JobRole = "Driver",
                            LastName = "Kierwoca",
                            PhoneNumber = "444222333",
                            ZipCode = "32-200"
                        },
                        new
                        {
                            EmployeeId = new Guid("b87815c1-8312-4856-9335-a272a57dbd62"),
                            Address = "Pawia 5",
                            BirthDate = new DateTime(2021, 11, 1, 22, 50, 32, 731, DateTimeKind.Local).AddTicks(7755),
                            City = "Cracov",
                            Email = "kasia@mail.com",
                            FirstName = "Katarzyna",
                            Gender = "Female",
                            HireDate = new DateTime(2021, 11, 1, 22, 50, 32, 731, DateTimeKind.Local).AddTicks(7758),
                            JobRole = "Manager",
                            LastName = "Obokmlyna",
                            PhoneNumber = "999222333",
                            ZipCode = "32-200"
                        });
                });

            modelBuilder.Entity("RistoranteMVC.Domain.Entities.Dish", b =>
                {
                    b.HasOne("RistoranteMVC.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
