// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RistoranteMVC.Models;

namespace RistoranteMVC.Migrations
{
    [DbContext(typeof(RistoranteMVCDbContext))]
    [Migration("20211011120212_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RistoranteMVC.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("9bcd1113-6b23-4493-bc83-0c80a436430a"),
                            Name = "Pizzas"
                        },
                        new
                        {
                            CategoryId = new Guid("a4b49c2f-93b6-42c7-99c6-524638667afd"),
                            Name = "Pastas"
                        },
                        new
                        {
                            CategoryId = new Guid("c85f1ad9-cef4-4bab-94da-e4dfb466c158"),
                            Name = "Soups"
                        },
                        new
                        {
                            CategoryId = new Guid("10895537-2732-403b-87dc-047ec2535593"),
                            Name = "Desserts"
                        },
                        new
                        {
                            CategoryId = new Guid("d99c5243-4815-4722-9fe3-e27623b8232b"),
                            Name = "Drinks"
                        });
                });

            modelBuilder.Entity("RistoranteMVC.Models.Coupon", b =>
                {
                    b.Property<Guid>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CouponName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<Guid?>("DishId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("OnAll")
                        .HasColumnType("bit");

                    b.Property<bool?>("OnCategory")
                        .HasColumnType("bit");

                    b.Property<bool?>("OnDish")
                        .HasColumnType("bit");

                    b.HasKey("CouponId");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("RistoranteMVC.Models.Dish", b =>
                {
                    b.Property<Guid>("DishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kcal")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Recommended")
                        .HasColumnType("bit");

                    b.HasKey("DishId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            DishId = new Guid("acf3b296-e0b4-4ff6-a5b8-25492aa78ce0"),
                            CategoryId = new Guid("9bcd1113-6b23-4493-bc83-0c80a436430a"),
                            Description = "Delicious classic from the pizza family",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 600,
                            Name = "Pizza margherita",
                            Price = 25.99m,
                            Recommended = true
                        },
                        new
                        {
                            DishId = new Guid("1edde71e-4146-4db3-aa01-f0c822f89375"),
                            CategoryId = new Guid("9bcd1113-6b23-4493-bc83-0c80a436430a"),
                            Description = "The best for meetings with friends",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 750,
                            Name = "Pizza salami",
                            Price = 31.50m,
                            Recommended = false
                        },
                        new
                        {
                            DishId = new Guid("6f9c3035-2056-413c-916b-80567f1e5ad1"),
                            CategoryId = new Guid("9bcd1113-6b23-4493-bc83-0c80a436430a"),
                            Description = "American pizza in the Italian version",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 800,
                            Name = "Pizza americana",
                            Price = 32.20m,
                            Recommended = false
                        },
                        new
                        {
                            DishId = new Guid("e84aecdd-205f-4da3-9621-70799479b8ad"),
                            CategoryId = new Guid("9bcd1113-6b23-4493-bc83-0c80a436430a"),
                            Description = "the best cheeses on your favorite pizza",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 900,
                            Name = "Four cheeses pizza",
                            Price = 33.90m,
                            Recommended = false
                        },
                        new
                        {
                            DishId = new Guid("e7346c59-22c7-48c5-8b75-7edd412a4cde"),
                            CategoryId = new Guid("a4b49c2f-93b6-42c7-99c6-524638667afd"),
                            Description = "The best pasta with classic bolognese sauce",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 450,
                            Name = "Spaghetti bolognese",
                            Price = 18.20m,
                            Recommended = false
                        },
                        new
                        {
                            DishId = new Guid("6d866692-40d6-4a7d-bbdb-b66b14637c0a"),
                            CategoryId = new Guid("a4b49c2f-93b6-42c7-99c6-524638667afd"),
                            Description = "Our kitchen's bestseller",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 550,
                            Name = "Spaghetti carbonara",
                            Price = 19.99m,
                            Recommended = true
                        },
                        new
                        {
                            DishId = new Guid("8b7ae5da-da0b-4dee-884f-33a8d71ef761"),
                            CategoryId = new Guid("a4b49c2f-93b6-42c7-99c6-524638667afd"),
                            Description = "For more hunger",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 840,
                            Name = "Lasagne",
                            Price = 36.99m,
                            Recommended = false
                        },
                        new
                        {
                            DishId = new Guid("798e5316-7d84-49f7-81dc-b3d0d8457b6f"),
                            CategoryId = new Guid("a4b49c2f-93b6-42c7-99c6-524638667afd"),
                            Description = "This taste will surprise you",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 410,
                            Name = "Tagliatelle with spinach",
                            Price = 19.99m,
                            Recommended = false
                        },
                        new
                        {
                            DishId = new Guid("a8f27650-3dfa-4cb7-b1ea-3523be7a6209"),
                            CategoryId = new Guid("c85f1ad9-cef4-4bab-94da-e4dfb466c158"),
                            Description = "Its taste comes from the best ingredients",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 180,
                            Name = "Creamy tomato soup",
                            Price = 12.99m,
                            Recommended = true
                        },
                        new
                        {
                            DishId = new Guid("a6ebc683-3ff4-4942-90d3-a47fc1d9e3f9"),
                            CategoryId = new Guid("c85f1ad9-cef4-4bab-94da-e4dfb466c158"),
                            Description = "Our novelty",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 210,
                            Name = "Curry soup",
                            Price = 13.30m,
                            Recommended = false
                        },
                        new
                        {
                            DishId = new Guid("533ea5dd-039f-4485-a335-1f9f20ebb202"),
                            CategoryId = new Guid("c85f1ad9-cef4-4bab-94da-e4dfb466c158"),
                            Description = "Tasty and nutritious",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 210,
                            Name = "Soup with meatballs",
                            Price = 15.95m,
                            Recommended = false
                        },
                        new
                        {
                            DishId = new Guid("3848e429-9ed6-4243-bfcf-89784957fccb"),
                            CategoryId = new Guid("c85f1ad9-cef4-4bab-94da-e4dfb466c158"),
                            Description = "Very aromatic dish that will delight everyone",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 210,
                            Name = "Mushroom soup",
                            Price = 14.49m,
                            Recommended = false
                        },
                        new
                        {
                            DishId = new Guid("6977356a-9b4f-4186-82d8-f62f5602e5e1"),
                            CategoryId = new Guid("10895537-2732-403b-87dc-047ec2535593"),
                            Description = "The best dessert that will impress your other half",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 300,
                            Name = "Tiramisu",
                            Price = 10.50m,
                            Recommended = true
                        },
                        new
                        {
                            DishId = new Guid("5e5348fb-555b-4482-9ca6-2d23e2304851"),
                            CategoryId = new Guid("10895537-2732-403b-87dc-047ec2535593"),
                            Description = "Melts in your mouth",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 290,
                            Name = "Panna Cotta",
                            Price = 10.40m,
                            Recommended = false
                        },
                        new
                        {
                            DishId = new Guid("94ec8d20-84d3-4f24-8d86-ed01c262884e"),
                            CategoryId = new Guid("10895537-2732-403b-87dc-047ec2535593"),
                            Description = "Sweet and cold what more could you want",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 260,
                            Name = "Ice-creams",
                            Price = 9.10m,
                            Recommended = false
                        },
                        new
                        {
                            DishId = new Guid("af208f65-15e0-49c4-80cf-1c113bcc7eb9"),
                            CategoryId = new Guid("10895537-2732-403b-87dc-047ec2535593"),
                            Description = "It is worth a try",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 270,
                            Name = "Granita",
                            Price = 10.05m,
                            Recommended = false
                        },
                        new
                        {
                            DishId = new Guid("72417ead-7712-4783-b72f-cc3bc8f08977"),
                            CategoryId = new Guid("d99c5243-4815-4722-9fe3-e27623b8232b"),
                            Description = "Just good coffee",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 10,
                            Name = "Coffee",
                            Price = 12.99m,
                            Recommended = true
                        },
                        new
                        {
                            DishId = new Guid("2e76d6a2-ae95-4510-8d54-78919f6f86f0"),
                            CategoryId = new Guid("d99c5243-4815-4722-9fe3-e27623b8232b"),
                            Description = "Just good tea",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 10,
                            Name = "Tea",
                            Price = 12.99m,
                            Recommended = false
                        },
                        new
                        {
                            DishId = new Guid("61adeaf0-d3ed-4732-ab58-7ae83492abcc"),
                            CategoryId = new Guid("d99c5243-4815-4722-9fe3-e27623b8232b"),
                            Description = "Just water",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 10,
                            Name = "Water",
                            Price = 12.99m,
                            Recommended = false
                        },
                        new
                        {
                            DishId = new Guid("76529e74-8e95-4375-8479-c3c5aa778cc6"),
                            CategoryId = new Guid("d99c5243-4815-4722-9fe3-e27623b8232b"),
                            Description = "Just Coca-Cola",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/13/18/38/silverware-1667988_960_720.png",
                            Kcal = 110,
                            Name = "Coca-Cola",
                            Price = 12.99m,
                            Recommended = false
                        });
                });

            modelBuilder.Entity("RistoranteMVC.Models.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderPlaced")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RistoranteMVC.Models.OrderDetail", b =>
                {
                    b.Property<Guid>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<Guid>("DishId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("DishId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("RistoranteMVC.Models.Dish", b =>
                {
                    b.HasOne("RistoranteMVC.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RistoranteMVC.Models.OrderDetail", b =>
                {
                    b.HasOne("RistoranteMVC.Models.Dish", "Dish")
                        .WithMany()
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RistoranteMVC.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RistoranteMVC.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
